local colors = {
-- PATCH_OPEN
Normal = {fg = "#C7C7C7", bg = "#000000"},
MiniStatuslineModeNormal = {link = "Normal"},
NormalNC = {link = "Normal"},
Bold = {bold = true},
Boolean = {fg = "#D8A2BE"},
Character = {fg = "#C5DEAB"},
ColorColumn = {bg = "#363636"},
Comment = {fg = "#758A99", italic = true},
Conceal = {fg = "#F0EFEF"},
Conditional = {fg = "#97B4ED"},
Constant = {fg = "#C2A1DD"},
Cursor = {fg = "#000000", bg = "#FFFFFF"},
TermCursor = {link = "Cursor"},
TermCursorNC = {link = "Cursor"},
CursorLine = {bg = "#292929"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#E6E6E6", bg = "#111113"},
ModeMsg = {link = "CursorLineNr"},
DiagnosticError = {fg = "#66FF87"},
DiagnosticHint = {fg = "#FF75F8"},
DiagnosticInfo = {fg = "#61D5FF"},
DiagnosticOk = {fg = "#66FFFF"},
DiagnosticUnderlineOk = {link = "DiagnosticOk"},
DiagnosticWarn = {fg = "#B3CBE6"},
DiffAdd = {fg = "#FFFFFF", bg = "#339933"},
DiffChange = {fg = "#FFFFFF", bg = "#667F1A"},
DiffDelete = {fg = "#FFFFFF", bg = "#803333"},
DiffText = {fg = "#FFFFFF", bg = "#44601A"},
Directory = {fg = "#CDDFEF"},
EndOfBuffer = {fg = "#878787"},
Error = {fg = "#66FF87", underdotted = true},
DiagnosticUnderlineError = {link = "Error"},
LspDiagnosticsDefaultError = {link = "Error"},
TroubleError = {link = "Error"},
ErrorMsg = {fg = "#FFFFFF", bg = "#803333"},
FloatBorder = {fg = "#6C6565", bg = "#000000"},
Folded = {fg = "#CCCCCC", bg = "#454545"},
FoldColumn = {link = "Folded"},
Function = {fg = "#A8B0FF"},
Identifier = {fg = "#CCD1CC"},
IncSearch = {fg = "#FFFFFF", bg = "#4D4D66"},
Italic = {italic = true},
LineNr = {fg = "#808099", bg = "#000000"},
LspDiagnosticsFloatingError = {link = "LspDiagnosticsDefaultError"},
LspDiagnosticsUnderlineError = {link = "LspDiagnosticsDefaultError"},
LspDiagnosticsVirtualTextError = {link = "LspDiagnosticsDefaultError"},
LspDiagnosticsDefaultHint = {fg = "#FF75F8", underdotted = true},
DiagnosticUnderlineHint = {link = "LspDiagnosticsDefaultHint"},
LspDiagnosticsFloatingHint = {link = "LspDiagnosticsDefaultHint"},
LspDiagnosticsUnderlineHint = {link = "LspDiagnosticsDefaultHint"},
LspDiagnosticsVirtualTextHint = {link = "LspDiagnosticsDefaultHint"},
TroubleHint = {link = "LspDiagnosticsDefaultHint"},
TroubleTextHint = {link = "LspDiagnosticsDefaultHint"},
LspDiagnosticsDefaultInformation = {fg = "#61D5FF", underdotted = true},
DiagnosticUnderlineInfo = {link = "LspDiagnosticsDefaultInformation"},
LspDiagnosticsFloatingInformation = {link = "LspDiagnosticsDefaultInformation"},
LspDiagnosticsUnderlineInformation = {link = "LspDiagnosticsDefaultInformation"},
LspDiagnosticsVirtualTextInformation = {link = "LspDiagnosticsDefaultInformation"},
TroubleInformation = {link = "LspDiagnosticsDefaultInformation"},
LspDiagnosticsDefaultWarning = {fg = "#B3CBE6", underdotted = true},
DiagnosticUnderlineWarn = {link = "LspDiagnosticsDefaultWarning"},
LspDiagnosticsFloatingWarning = {link = "LspDiagnosticsDefaultWarning"},
LspDiagnosticsUnderlineWarning = {link = "LspDiagnosticsDefaultWarning"},
LspDiagnosticsVirtualTextWarning = {link = "LspDiagnosticsDefaultWarning"},
TroubleWarning = {link = "LspDiagnosticsDefaultWarning"},
LspDiagnosticsSignError = {fg = "#66FF87"},
LspDiagnosticsSignHint = {fg = "#FF75F8"},
LspDiagnosticsSignInformation = {fg = "#61D5FF"},
LspDiagnosticsSignWarning = {fg = "#B3CBE6"},
MatchParen = {fg = "#FFFFFF", bg = "#333333"},
MiniStatuslineDevInfo = {fg = "#9496A8", bg = "#000000"},
MiniStatuslineFileinfo = {fg = "#9496A8", bg = "#000000"},
MiniStatuslineFilename = {fg = "#80778D", bg = "#000000"},
MiniStatuslineInactive = {fg = "#666666", bg = "#000000"},
MiniStatuslineModeCommand = {fg = "#FFCC66", bg = "#374367"},
MiniStatuslineModeInsert = {fg = "#8AFF8A", bg = "#194D32"},
MiniStatuslineModeOther = {fg = "#E6E6E6", bg = "#000000"},
MiniStatuslineModeReplace = {fg = "#FF6687", bg = "#523399"},
MoreMsg = {fg = "#FF94FF"},
Question = {link = "MoreMsg"},
NeoTreeTabSeparatorActive = {fg = "#FFFFFF", bg = "#454545"},
NeoTreeTabSeparatorInactive = {fg = "#454545", bg = "#121212"},
NeoTreeTitleBar = {fg = "#FFFFFF", bg = "#454545"},
NormalFloat = {fg = "#E6E6E6", bg = "#121212"},
Number = {fg = "#99D1FF"},
Float = {link = "Number"},
NvimInternalError = {fg = "#FFCC66", bg = "#803333"},
Pmenu = {fg = "#DEDEDE", bg = "#4F4F4F"},
PmenuSbar = {bg = "#404040"},
PmenuSel = {bg = "#666666"},
PreProc = {fg = "#FFE0FB"},
Repeat = {fg = "#A1A1ED"},
Search = {fg = "#FFFFFF", bg = "#4B2BBF", underdotted = true},
SignColumn = {bg = "#000000"},
Special = {fg = "#808099"},
SpellBad = {fg = "#66FF87", undercurl = true},
SpellCap = {fg = "#6565B3", undercurl = true},
Statement = {fg = "#B6C6F7"},
StatusLine = {fg = "#D4D4D4", bg = "#454545"},
StatusLineNC = {fg = "#DEDEDE", bg = "#454545"},
StorageClass = {fg = "#F2998D"},
String = {fg = "#AAD5AF"},
Structure = {fg = "#E9A0C6"},
Substitute = {fg = "#FFFFFF", bg = "#7E2020"},
Title = {fg = "#FFEA47"},
Todo = {fg = "#80CBE0", underdotted = true},
TroubleSignError = {fg = "#66FF87"},
TroubleSignHint = {fg = "#FF75F8"},
TroubleSignInformation = {fg = "#61D5FF"},
TroubleSignOther = {fg = "#FFFFFF"},
TroubleSignWarning = {fg = "#B3CBE6"},
Type = {fg = "#F4B071"},
Typedef = {fg = "#CEAE6F"},
Underlined = {underdashed = true},
VertSplit = {fg = "#BBAAAA"},
Visual = {fg = "#DEDEDE", bg = "#333399"},
MiniStatuslineModeVisual = {link = "Visual"},
WarningMsg = {fg = "#FF9233"},
Whitespace = {fg = "#545454"},
lCursor = {fg = "#242424", bg = "#EDDEDE"},
CursorIM = {link = "lCursor"},
-- PATCH_CLOSE
}

vim.cmd("set background=dark")
vim.cmd("highlight clear")
vim.cmd("syntax reset")
vim.g.colors_name = "jdark"

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

